#!/bin/bash
# FarmFresh Site Cleanup - Deletion Script (Reference)
# This is a reference guide showing which files to delete
# ALWAYS BACKUP before deleting!

echo "=========================================="
echo "FarmFresh Site Cleanup - Deletion List"
echo "=========================================="
echo ""
echo "⚠️  BACKUP BEFORE EXECUTING!"
echo ""

# DELETE EXECUTABLES & ARCHIVES
echo "1. DELETE EXECUTABLES & ARCHIVES (4 files):"
echo "   cmd.exe"
echo "   static/images/python-3.13.1-amd64.exe"
echo "   static/images/_Getintopc.com_Sublime_Text_4_Build_4126.rar"
echo "   static/images/site.code-workspace"
echo ""

# DELETE IMAGE DUPLICATES
echo "2. DELETE IMAGE DUPLICATES (67 files):"
echo ""
echo "   CAMEL DUPLICATES (5 to delete):"
echo "   - cam3.jpg"
echo "   - cam4.jpg"
echo "   - cam5.jpg"
echo "   - cam6.jpg"
echo "   - cam7.jpg"
echo ""

echo "   GOAT DUPLICATES (8 to delete):"
echo "   - g2.jpeg"
echo "   - g3.jpg"
echo "   - g4.jpeg"
echo "   - g5.jpeg"
echo "   - g6.jpeg"
echo "   - g7.jpeg"
echo "   - g8.jpeg"
echo "   - g9.jpeg"
echo ""

echo "   GUINEA FOWL DUPLICATES (5 to delete):"
echo "   - gui3.jpeg"
echo "   - gui4.jpeg"
echo "   - gui7.jpeg"
echo "   - guin1.webp"
echo "   - guineaf.jpeg"
echo ""

echo "   RABBIT DUPLICATES (6 to delete):"
echo "   - rab4.jpeg"
echo "   - rab6.jpeg"
echo "   - rab7.jpeg"
echo "   - rabits.jpeg"
echo "   - rabz.jpeg"
echo "   - rabfat.jpg"
echo ""

echo "   SHEEP DUPLICATES (3 to delete):"
echo "   - sh1.jpeg"
echo "   - sh2.jpeg"
echo "   - sh4.jpeg"
echo ""

echo "   POULTRY DUPLICATES (6 to delete):"
echo "   - hen1.jpeg"
echo "   - fowl1.jpeg"
echo "   - redh.jpeg"
echo "   - wh1.jpeg"
echo "   - wh2.jpeg"
echo "   - wcock.jpeg"
echo ""

echo "   FRUIT/GENERIC IMAGE DUPLICATES (12 to delete):"
echo "   - Fruit-Names-in-English~14.jpg"
echo "   - Fruit-Names-in-English~15.jpg"
echo "   - fru.jpg"
echo "   - veges.jpg"
echo "   - vetables.png"
echo "   - corn .jpg"
echo "   - cumcumber.jpg"
echo "   - AdobeStock_249933303_Preview (1).jpeg"
echo "   - AdobeStock_320398182_Preview (1).jpeg"
echo "   - aa7c6f80-099e-4ecc-aadc-fd7a72408b81~7.png"
echo "   - aa7c6f80-099e-4ecc-aadc-fd7a72408b81~8.png"
echo "   - aa7c6f80-099e-4ecc-aadc-fd7a72408b81~10.png"
echo "   - aa7c6f80-099e-4ecc-aadc-fd7a72408b81~11.png"
echo "   - aa7c6f80-099e-4ecc-aadc-fd7a72408b81~12.png"
echo ""

echo "   ORPHANED IMAGES (3 to delete):"
echo "   - 9168a8879330db3008cbb48455bf5370.jpg"
echo "   - images.jpeg"
echo "   - jar.jpg"
echo ""

# DELETE HTML TEMPLATES
echo "3. DELETE HTML TEMPLATES (8 files):"
echo "   - templates/+.html"
echo "   - templates/template.html"
echo "   - templates/livestock1.html"
echo "   - templates/cow.html"
echo "   - templates/cows.html"
echo "   - templates/goats.html"
echo "   - templates/sheep.html"
echo "   - templates/rabit.html"
echo ""

echo "=========================================="
echo "TOTAL DELETIONS: 85-95 files"
echo "ESTIMATED SPACE FREED: 50-100 MB"
echo "=========================================="
echo ""
echo "NEXT STEPS:"
echo "1. BACKUP static/images/ directory"
echo "2. Review AUDIT_REPORT.md for details"
echo "3. Delete files in order above"
echo "4. Create new folder structure"
echo "5. Update code references to images"
echo "6. Run Flask app and test all pages"
echo ""
echo "=========================================="
